/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as v2Core from "./v2-core";
import type * as v2Periphery from "./v2-periphery";

export type { v2Core };

export type { v2Periphery };
